### ISSUE TITLE
Null Reference exception in InProc mode

### ISSUE THREAD

**Issue by faraazaamir** [aspnet/AspNetSessionState#101]
When using SessionStateModuleAsync (2.0.0) in InProc mode, I get the following exception when the application is launched. With version 1.1.0 there is no error, but with version 2.0.0 the below exception is thrown. Please advise:

Object reference not set to an instance of an object.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:

[NullReferenceException: Object reference not set to an instance of an object.]
   Microsoft.AspNet.SessionState.SessionStateStoreProviderAsyncBase.Initialize(String name, NameValueCollection config) +45
   Microsoft.AspNet.SessionState.InProcSessionStateStoreAsync.Initialize(String name, NameValueCollection config) +48
   Microsoft.AspNet.SessionState.SessionStateModuleAsync.InitModuleFromConfig(HttpApplication app, SessionStateSection config) +696
   Microsoft.AspNet.SessionState.SessionStateModuleAsync.Init(HttpApplication app) +234
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +586
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +254
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +346

[HttpException (0x80004005): Object reference not set to an instance of an object.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +552
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +122
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +737

**Comment by sharadshahihw** [comment]
I got the exception too. There's a pull request which fixes it.
https://github.com/aspnet/AspNetSessionState/pull/98

**Comment by Dhugal** [comment]
We're hitting this issue too - can the PR be merged and released, please?

**Comment by StephenMolloy** [comment]
As mentioned above, this is fixed by #98 which was recently merged. Will be available when next release drops.

**Comment by DaleyKD** [comment]
I don't mean to be rude, but is there any idea when this will be released? We just upgraded to v2.0 this weekend, and have to rollback so we can keep working.
