### ISSUE TITLE
HttpContext in Session_Start

### ISSUE THREAD

**Issue by Embo1** [aspnet/AspNetSessionState#12]
I have asked this question on SO https://stackoverflow.com/questions/53533474/session-start-and-asp-net-async-sessionstate-module

Is it possible the HttpContext.Current is null in Session_Start with the async provider?

**Comment by StephenMolloy** [comment]
There do appear to be some async paths involved there. Once you give up the thread, anything can happen. I wouldn't expect to see the current context as null very often. But that could indicate something else went wrong when initializing the request. A null-check combined with some logging as suggested in the SO link might shed some light on why HttpContext.Current becomes null.
