### ISSUE TITLE
32 partitions in cosmos db

### ISSUE THREAD

**Issue by abppriya** [aspnet/AspNetSessionState#21]
Cosmos DB provides unlimited partitions , why hard coding the number of partition keys to 32, you are potentially creating a skewed usage of the physical partitions in the cosmos DB.

**Comment by koichino** [comment]
There is  a comment saying only 32 partitions can be created at Row 961 to 963 in the source code.  
My customer expected to use partitions more than 32. So need to update.
And why only 32 expexted when writing this code?

**Comment by StephenMolloy** [comment]
Fixed with #24
