### ISSUE TITLE
.NET Framework 4.7.2 Compatibility

### ISSUE THREAD

**Issue by MSC-CWebber** [aspnet/AspNetSessionState#30]
We are using CosmosDBSessionStateProviderAsync with .NET Framework 4.7.2 and had run into some issues with documents not being written. I have a ticket open with Microsoft to troubleshoot those issues on the CosmosDB side, but we were asked to verify here that this library is indeed 4.7.2 Compatible or if there are any known issues with running it against 4.7.2. Any insight would be appreciated.

**Comment by StephenMolloy** [comment]
I don't know what you mean or if there is some nuance I am missing when you ask if this library is "4.7.2 Compatible." The hooks needed to support this new session state module were added to the .Net framework in 4.6.2. Thus, the libraries here are built to target 4.6.2 and newer. There should not be any issues with using these packages in a project that targets 4.7.2.
