### ISSUE TITLE
Sliding timeout may cause Cosmos 449 response

### ISSUE THREAD

**Issue by qxx** [aspnet/AspNetSessionState#35]
This is regarding the CosmosDBSessionStateProviderAsync. Using AspNetSessionState 1.1.0 and Microsoft.Azure.DocumentDB 1.15.0.

In stored procedures ResetItemTimeout and also GetStateItem there is this snippet
```
// using write operation to reset the TTL
var isAccepted = collection.replaceDocument(doc._self, doc,
  function(err, updatedDocument, responseOptions) {
    if (err)
    {
      throw err;
    }
    response.setBody({ updated: true });
  });
```
This resets the timeout on every read (and done twice essentially). It's how sliding timeout supposed to work, but also causing performance problems. It turns every read operation into a write. Even though Cosmos is very fast in write, when there are concurrent requests trying to read the SessionStateItem, we start to get 449 responses like this
```
Microsoft.Azure.Documents.RetryWithException:
Message: {"Errors":["Conflicting request to resource has been attempted. Retry to avoid conflicts."]}
```
Most of these 449s can recover in cosmos client's internal retries, a few will eventually fail and throw. And those recovered will leave us a few seconds delay due to the auto-backoff.

We added a check in the SPs so it only resets ttl when it's already half way through, inspired by FormsAuthentication's sliding expiration, which helps us avoid the 449s in a read-heavy application. 

I wonder if you guys have any plan for performance improvements, making the sliding strategy configurable etc?

**Comment by StephenMolloy** [comment]
This is an interesting proposal. The nature of Session State in ASP.Net and this async module in particular means that we don't actually know how much time is left before expiration until we are already in the stored procedures here. Looking through the stored procedures, it looks to me like you have identified the only two places where we "update" just for the sake of resetting the timeout without actually updating data. So non-exclusive Get's and end-of-request releases are the only two places we would see any benefit here.

The work to enable this is not crazy complicated, but it is not trivial either. If it could be applied more broadly to this provider or even other session providers, I would probably spend more time pursuing this. However, it seems like introducing a new concept with such a limited applicability might be confusing - Why it works sometimes and why it doesn't at other times; Which providers do this and which ones don't.

One thing to note is that V1.X of this async session state module would register itself only with the 'integratedMode' precondition. The in-box synchronous session providers used the 'managedHandler' precondition so the wouldn't run on _all_ requests including requests for static files. The next release of this async session suite will also re-introduce this precondition. Hopefully that has an impact on the amount of contention being seen here so these errors become much fewer.

I'm going to leave this issue open for the time being if anybody wants to comment. But I don't currently plan to introduce this in the next release.

**Comment by StephenMolloy** [comment]
I also saw there was [another request](#40) for something similar in the SQL provider. So I'm trying a less-precise approach to the problem. PR #40 will allow providers to skip the call to reset the timeout on requests that never read or updated session state. This is not exactly the same approach described above, but I think it will yield a similar reduction in contention here.
