### ISSUE TITLE
Specify strong consistency level explicitly in the CosmosClient

### ISSUE THREAD

**Issue by george-polevoy** [aspnet/AspNetSessionState#42]
This code does not work with default consistency guarantees of the CosmosDB account (Session consistency).
So if you just use the default settings for Azure Cosmos DB (session consistency) there will be consistency errors.

Consider adding following, so it would throw exception if account consistency mode is not Strong.

``` C#
new CosmosClient(...
new CosmosClientOptions
{
    ConsistencyLevel = ConsistencyLevel.Strong
})
```

**Comment by StephenMolloy** [comment]
I don't believe that Session State necessarily requires "Strong" consistency. So I'm going to leave the default as unspecified/Session. However, I have added a 'consistencyLevel' option to the provider that will let you specify something different.

Fixed in #79
