### ISSUE TITLE
Excessive load on Cosmos Session Provider that its exceeding RUs even with single user

### ISSUE THREAD

**Issue by zeshan-iqbal** [aspnet/AspNetSessionState#45]
I have below configuration of CosmosSessionProvider 

`<providers>
        <add name="CosmosDBSessionStateProviderAsync"
             cosmosDBEndPointSettingKey="sessionCosmsosDatabaseEndPoint"
             cosmosDBAuthKeySettingKey="sessionCosmsosDatabaseAuthKey"
             databaseId="session_db"
             collectionId="merchantportal_cn"
             offerThroughput="5000"
             connectionMode="Direct"
             connectionProtocol="Tcp"
             requestTimeout="5"
             maxConnectionLimit="50"
             maxRetryAttemptsOnThrottledRequests="10"
             maxRetryWaitTimeInSeconds="10"
             preferredLocations=""
             partitionKey=""
             partitionNumUsedByProvider=""
             type="Microsoft.AspNet.SessionState.CosmosDBSessionStateProviderAsync, Microsoft.AspNet.SessionState.CosmosDBSessionStateProviderAsync, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
      </providers>`

I'm testing app with single user and its exceeding 5000 RU's and throwing below error message

**`The request rate to CosmosDB is too large. You may consider to increase the offer throughput of the CosmosDB collection or increase maxRetryAttemptsOnThrottledRequests and maxRetryWaitTimeInSeconds settings in web.config`**

I tried exceeding maxRetryAttemptsOnThrottledRequests  and maxRetryWaitTimeInSeconds but it didn't helped. Any suggestion to make cosmos session perform better.

**Note:** In Azure portal I see I'm making 300-350 requests per minute while I'm just browsing the app .

Any help or pointer would be much appreciated.

**Comment by nomada2** [comment]
Hi @ zeshan-iqbal, have you tried to reproduce this behavior in the local Azure Cosmos DB emulator? I am very interested in using this session provider and just came across it today.

In the next few days, I will do some tests, to see if the error is reproduced

**Comment by zeshan-iqbal** [comment]
@nomada2, Yes, I'm able to reproduce this on emulator.

**Comment by StephenMolloy** [comment]
A couple of suggestions. The first obviously is to check your actual throughput configuration. The option on the provider definition is only used when the provider has to create a new cosmos container. If one already exists, it will simply use that and whatever throughput is defined for it. (The [next release](#68) will allow using a pre-provisioned throughput number across all containers by setting 'offerThroughput' to "0" - but 5000 will still be default if nothing is specified.)

The second thing I would look at is changing the preCondition for the async session module to add 'managedHandler'. This is also a [change coming in the next release](#78) - but there is no reason you can't change it in config on your own right now. Presumably casual browsing of an app does not generate 300+ primary requests, which means a high number of those requests are probably for non-managed things like images. Hopefully adding the 'managedHandler' precondition will get your requests that use session state down quite a bit. I don't think the API should be that noisy for a reasonable request rate.

Please feel free to re-open if you still see problems after following these suggestions.

**Comment by StephenMolloy** [comment]
Oh, one final suggestion. PR #80 introduces a new setting to enable skipping a call to reset the state timeout by requests that didn't use session state. This can help in applications that disable state when not needed - MVC-style apps with controllers that get called frequently and don't use session state are good examples. This isn't something you can try just yet on your own, but I expect it will be another setting available in the next release.
