### ISSUE TITLE
SessionID sync between apps

### ISSUE THREAD

**Issue by jsmith614** [aspnet/AspNetSessionState#51]
Hi, 
I'm working with two different applications. One (app1) is on .net 3.5, the other (app2) on .net 4.8.

I need both apps to share session, which I had them doing when I was using the default SqlServer sessionState option between them by using the reflection module found here (https://www.codeproject.com/Articles/27090/Sharing-Session-Across-Applications) by using the same application name and machine key.

However, when I switch to using SqlSessionStateProviderAsync in app2, the two apps use different SessionIDs and thus do not share session anymore. I've looked though the source here and see that the _idManager.CreateSessionID and GetSessionID are being called with the context, and nothing appears different that I can see, so I'm not sure why it's not using the same SessionID.

- For app1, I have the equivalent of:

`<sessionState mode="SQLServer" sqlConnectionString="data source= testtest\SQL2017; integrated security=true;Application Name=AppName123" timeout="5"></sessionState>`

- For app2, I have the same web config as listed in the description for this project:

`    <sessionState cookieless="false" regenerateExpiredSessionId="true" mode="Custom" customProvider="SqlSessionStateProviderAsync" timeout="5">
      <providers>
        <add name="SqlSessionStateProviderAsync" connectionStringName="ASPState" UseInMemoryTable="false" MaxRetryNumber="10" RetryInterval="0.001"
          type="Microsoft.AspNet.SessionState.SqlSessionStateProviderAsync, Microsoft.AspNet.SessionState.SqlSessionStateProviderAsync, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"/>
      </providers>
    </sessionState>`

Any help here would be appreciated, thanks!

**Comment by StephenMolloy** [comment]
What you are trying to accomplish - sharing state between two separate applications - is not recommended and is technically not supported. We realize that people do do this often, but responding to this issue does not condone such a pattern. We have specifically declined to support such a scenario before (#19) and will continue to do so in the future.

With that said... the async SQL provider does indeed obtain session ID's from the ID Manager like the other session providers. But it also appends the AppId to the SessionId to prevent apps from sharing state. See https://github.com/aspnet/AspNetSessionState/blob/4a58f9926fd1f7b6ee4f06dbf56ff9c3cff76a72/src/SqlSessionStateProviderAsync/SqlSessionStateProviderAsync.cs#L356-L362 for one example, or search for 'AppendAppIdHash' to see where we do that. There is not a quick and easy way to get around this. However, there are unofficial ways to work around this. The internet has quietly discussed hacking the AppId for years. Using this repo alone, it would be easy enough to subclass the async sql provider and fiddle with the AppId property upon initialization of your derived class. But again, you do so at your own risk as sharing session state between apps is not a supported scenario.

**Comment by jsmith614** [comment]
Thanks! 
I noticed that the formatting logic for the AppID is `appId.GetHashCode().ToString("X8", CultureInfo.InvariantCulture);`, which produces the same string in both apps, but the app1, using the SqlServer method generates a different string for the AppID, so it seems it's not using that `GetHashCode().ToString(X8)`, or does it in a different manner, so I'm trying to figure out what logic it uses for that.
