### ISSUE TITLE
multiple non-blocking requests

### ISSUE THREAD

**Issue by jsmith614** [aspnet/AspNetSessionState#52]
Hi, I've implemented the SqlSessionStateProviderAsync with all the default settings and it is working mostly as expected. However, it still seems to be blocking simultaneous requests like the default session state does. I've tried many things to remedy this, but I'm beginning to think I misunderstood the purpose of this provider, so I wanted to ask and make sure that this provided was intended to allow simultaneous requests without blocking before banging my head against it some more.

**Comment by martincventer** [comment]
Did you specify the appsetting?

	<add key="aspnet:AllowConcurrentRequestsPerSession" value="true" />

**Comment by jsmith614** [comment]
I did not! I must have missed that. I will try it immediately.
