### ISSUE TITLE
SessionItemLong output parameter missing from GetSessionStateItemAsync

### ISSUE THREAD

**Issue by jsmith614** [aspnet/AspNetSessionState#53]
Hi,
I've noticed an issue with the GetSessionStateItemAsync method in SqlSessionStateRepository.cs.

There is an expected output parameter, SessionItemLong, that is not being provided. It looks like it's trying to retrieve this parameter when the database get operation fails, perhaps as some sort of caching. This may be an incorrect interpretation of its purpose. The code is shown below, with the red box indicating the issue.

My question is, what is the purpose of the code outlined in the red box? Is it necessary to be here and what would be the consequences of simply removing it? If it's necessary, then it seems a number of changes will need to be made in many places to accommodate the addition of this parameter, given that the AddSessionItemLongParameter method in SqlParamterCollectionExtension takes in some extra arguments.

SqlSessionStateRepository:
![image](https://user-images.githubusercontent.com/33847368/119697263-04937100-be1e-11eb-9929-9361ad6cbba9.png)

SqlCommandHelper:
![image](https://user-images.githubusercontent.com/33847368/119697508-415f6800-be1e-11eb-92ff-9593f2aa8b33.png)

**Comment by jsmith614** [comment]
I believe I see what happened here. SessionItemShort is not used in this provider, whereas it was previously used in the older SqlServer provider. In the older version, SessionItemShort was the output parameter, while SessionItemLong was the main return value.
![image](https://user-images.githubusercontent.com/33847368/119704158-5095e400-be25-11eb-9dbc-85f8170b2afa.png)

I assume that the old code was checking for the SessionItemShort output value if the main return value of SessionItemLong was null. Likely this output parameter line was added when attempting to replicate the old code and SessionItemShort was simply replaced with SessionItemLong without realizing that it was not longer included.

Just an idea, but it seems the most plausible explanation. That would mean the best solution here would be to remove the code in the red box.

**Comment by martincventer** [comment]
I have a pretty rock solid implementation running at the moment and we've gone through this exact journey of the old provider to the async one.  If you need help I'd be happy assist? martinc.venter[at]gmail.com

**Comment by martincventer** [comment]
I don't think this is a use case that was originally intended to be supported, but we've actually done much of the same.  Feel free to get in touch if you are still having issues with this?

**Comment by jsmith614** [comment]
I've actually figured out a simple work-around for now by setting a dummy session value greater than 7kb in size on session start to force SessionItemLong to be used.  This should work for the duration that I need to support backwards compatibility with an older version of .net. At least until I hit my next issue that requires more custom modifications :)

That said, if I'm right about the reason for this line of code existing, then it should probably be removed anyway. I want to leave this open a bit longer, if only to find out if I'm right about that.

**Comment by martincventer** [comment]
How many concurrent users do you need to support and how frequent are requests hitting your servers for those users?  We've had to adapt quite a few things from the original solution, we also found that scaling issues as we added more and more nodes in our web farm.  This won't be an issue for a low number of servers but as you scale out it becomes rather tedious.  Every node fires off a call to delete expired sessions.  We also had issues with our log performance at scale, are you seeing any of these issues on your side?

**Comment by jsmith614** [comment]
I haven't deployed this outside of a dev environment yet, but we currently only use two servers in production with probably 20 users max at any given time (though that number is a wild guess, it's certainly less than 100). For any given user, we may have five to ten requests hitting the server for a page load, with maybe one to three for user input. We do use SignalR, so we have occasional requests being made that way, which is what sparked the need to handle session expiration manually.

I am curious about the scaling issues. I don't know that we'll ever have a larger number of servers but it would be good to plan ahead if possible. I haven't noticed any logging issues.

**Comment by jsmith614** [comment]
Thanks! I don't have any outstanding issues at the moment, but I'd love to
take you up on that when I inevitably do later.

**Comment by StephenMolloy** [comment]
Should be addressed with all the many changes in #75, although there has not been extensive testing done on such a big change yet.
