### ISSUE TITLE
SessionID problem with Database collation 

### ISSUE THREAD

**Issue by migochoa73** [aspnet/AspNetSessionState#55]
When the SQL database have a gobal collation in Latin1_General_BIN, have problem with the field Session**ID** and Session**Id**, the query in the file SqlInMemoryTableSessionStateRepository.cs in the lines 72 and 77 build the WHERE with SessionID with the last D in upper case and give errors because not find this field

Is possible to all SessionId in this file have the exactly same name

**Comment by StephenMolloy** [comment]
Fixed by #77
