### ISSUE TITLE
Session State Module Runs for Non-Managed Requests

### ISSUE THREAD

**Issue by jbparker** [aspnet/AspNetSessionState#59]
The [web.config snippet shows](https://github.com/aspnet/AspNetSessionState#replace-the-existing-session-module-in-webconfig) removing the old session state module and adding the new async module:

```xml
  <system.webServer>
    <modules>
      <!-- remove the existing Session state module -->
      <remove name="Session" />
      <add name="Session" preCondition="integratedMode" type="Microsoft.AspNet.SessionState.SessionStateModuleAsync, Microsoft.AspNet.SessionState.SessionStateModule, Version=1.1.0.0, Culture=neutral" />
    </modules>
  </system.webServer>
```

The [preCondition](https://docs.microsoft.com/en-us/previous-versions/iis/settings-schema/ms690693(v=vs.90)#attributes) of **integratedMode** makes sense to include here, but without specifying the **managedHandler** value, the module will potentially be run for non-managed requests (e.g., images, scripts, etc) that do not require session state.

We recently ran into a problem installing this module where many non-managed requests overwhelmed the session provider since their pipelines now included the session module. The previous session module _specifies **managedHandler** as well_, so it seems that running for non-managed requests by default is (arguably, at least) a regression.

Would a PR that changes the example code to include **managedHandler** be desirable, and, if not, does putting a blurb about this  near that snippet make sense?

**Comment by StephenMolloy** [comment]
Makes sense. The original in-box SessionState module was preconditioned on managed handlers as well. This change is easily undone by anyone who really needs to run the module on all requests.

Fixed by #78
